name = "Sarthak kaushik";
console.log(name);
age = 19;
console.log(age);
a = null;
console.log(a);
b = true;
console.log(b);
c = false;
console.log(c);
d = undefined;
console.log(d);
let fullName = "Sarthak Kaushik son of Mukesh Chandra Sharma";
console.log(fullName);
var nammme = "Sarthak Kaushik";
console.log(nammme);
var namme = "kanika Kaushik";
console.log(namme);
fulllName = "Sarthak Kaushik son of Bhavna Sharma";
console.log(fulllName);